import { Router, Request, Response, NextFunction } from 'express';
import { z } from 'zod';
import prisma from '../config/database.js';
import { generateId } from '../common/utils/uuid.js';
import { authMiddleware, requirePermissions, AuthenticatedUser } from '../common/middleware/auth.js';
import { createAuditLog } from '../audit/audit.service.js';
import { AppError } from '../common/middleware/errorHandler.js';
import { config } from '../config/env.js';
import multer from 'multer';
import { fileTypeFromBuffer } from 'file-type';
import jwt from 'jsonwebtoken';
import path from 'path';
import fs from 'fs';

// Constants for local storage
const STORAGE_DIR = path.join(process.cwd(), 'storage', 'documents');
if (!fs.existsSync(STORAGE_DIR)) {
  fs.mkdirSync(STORAGE_DIR, { recursive: true });
}

// Set up multer memory storage first so we can validate magic bytes before saving to disk
const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 10 * 1024 * 1024 }, // 10MB limit
});

const router = Router();

/**
 * GET /api/documents/serve
 * Serve a document securely using a short-lived JWT token generated by the presign endpoint.
 * Notice: This is purposefully unauthenticated by middleware because the token itself IS the auth.
 */
router.get('/serve', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const token = req.query.token as string;
    if (!token) {
      throw new AppError(401, 'UNAUTHORIZED', 'Missing download token.');
    }

    // Verify token
    const secret = process.env.JWT_SECRET || 'fallback-secret';
    let payload: any;
    try {
      payload = jwt.verify(token, secret);
    } catch (err) {
      throw new AppError(401, 'UNAUTHORIZED', 'Invalid or expired download token.');
    }

    const documentId = payload.documentId;
    const document = await prisma.document.findUnique({ where: { id: documentId } });
    
    if (!document) {
      throw new AppError(404, 'NOT_FOUND', 'Document not found.');
    }

    const filePath = path.join(STORAGE_DIR, document.storage_key);
    if (!fs.existsSync(filePath)) {
      throw new AppError(404, 'NOT_FOUND', 'File not found on disk.');
    }

    res.setHeader('Content-Type', document.mime_type);
    res.setHeader('Content-Disposition', `inline; filename="${document.filename}"`);
    res.sendFile(filePath);
  } catch (err) {
    next(err);
  }
});

router.use(authMiddleware);

/**
 * POST /api/documents/upload
 * Upload a document (e.g. for excuse letters or requests).
 * Restricts to Student, Teacher, Staff, or Admin.
 */
router.post('/upload', upload.single('file'), async (req: Request, res: Response, next: NextFunction) => {
  try {
    const authUser = (req as any).user as AuthenticatedUser;
    
    // 1. Role Check
    const allowedRoles = ['Student', 'Teacher', 'Staff', 'Admin'];
    const hasAccess = authUser.roles.some(r => allowedRoles.includes(r));
    if (!hasAccess) {
      throw new AppError(403, 'FORBIDDEN', 'Your role is not allowed to upload documents.');
    }

    // 2. File Check
    const file = req.file;
    if (!file) {
      throw new AppError(400, 'BAD_REQUEST', 'No file provided.');
    }

    // 3. Prevent Storage Exhaustion (Max 10 uploads per user per 24h)
    const twentyFourHoursAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const recentUploadCount = await prisma.document.count({
      where: {
        uploaded_by: authUser.id,
        created_at: { gte: twentyFourHoursAgo }
      }
    });

    if (recentUploadCount >= 10) {
      throw new AppError(429, 'TOO_MANY_REQUESTS', 'You have reached the maximum number of file uploads allowed per day.');
    }

    // 4. Magic Bytes Validation
    const fileType = await fileTypeFromBuffer(file.buffer);
    const allowedMimeTypes = ['application/pdf', 'image/jpeg', 'image/png'];
    
    if (!fileType || !allowedMimeTypes.includes(fileType.mime)) {
      throw new AppError(400, 'BAD_REQUEST', 'Invalid file type. Only PDF, JPEG, and PNG are allowed.');
    }

    // 5. Save to Disk
    const storageKey = `${generateId()}${fileType.ext ? '.' + fileType.ext : ''}`;
    const filePath = path.join(STORAGE_DIR, storageKey);
    fs.writeFileSync(filePath, file.buffer);

    // 6. Create DB Record
    const documentRecord = await prisma.document.create({
      data: {
        id: generateId(),
        storage_key: storageKey,
        filename: file.originalname,
        mime_type: fileType.mime,
        size_bytes: file.size,
        uploaded_by: authUser.id,
      }
    });

    // 7. Audit Log
    const correlationId = (req as any).correlationId;
    await createAuditLog({
      actorUserId: authUser.id,
      action: 'DOCUMENT_UPLOADED',
      resourceType: 'document',
      resourceId: documentRecord.id,
      newState: { filename: documentRecord.filename, mime_type: documentRecord.mime_type, size_bytes: documentRecord.size_bytes },
      correlationId,
    });

    res.status(201).json({ success: true, data: documentRecord });
  } catch (err) {
    next(err);
  }
});

const requestDocumentSchema = z.object({
  studentId: z.string().min(1),
  documentType: z.string().min(1),
  purpose: z.string().min(1),
});

const approveDocumentSchema = z.object({
  stage: z.enum(['teacher', 'principal', 'registrar']),
  remarks: z.string().optional(),
  status: z.enum(['Approved', 'Rejected', 'Ready for Pickup', 'Completed']),
});

/**
 * POST /api/documents/requests
 * Submit a new document request.
 */
router.post('/requests', requirePermissions('document:request'), async (req: Request, res: Response, next: NextFunction) => {
  try {
    const input = requestDocumentSchema.parse(req.body);
    const correlationId = (req as any).correlationId;
    const actorId = ((req as any).user as AuthenticatedUser).id;

    // Resolve student info
    const student = await prisma.student.findUnique({
      where: { user_id: input.studentId },
      include: { user: true }
    });

    if (!student) {
      throw new AppError(404, 'NOT_FOUND', 'Student profile not found.');
    }

    const request = await prisma.documentRequest.create({
      data: {
        id: generateId(),
        student_id: input.studentId,
        document_type: input.documentType,
        purpose: input.purpose,
        status: 'Submitted',
        current_stage: 1,
      }
    });

    await createAuditLog({
      actorUserId: actorId,
      action: 'DOCUMENT_REQUEST_CREATED',
      resourceType: 'document_request',
      resourceId: request.id,
      newState: { documentType: input.documentType, purpose: input.purpose },
      correlationId,
    });

    res.status(201).json({ success: true, data: request });
  } catch (err) {
    next(err);
  }
});

const updateDocumentRequestSchema = z.object({
  status: z.string().optional(),
  currentStage: z.number().optional(),
  teacherApprovedDate: z.string().optional(),
  teacherRemarks: z.string().optional(),
  principalApprovedDate: z.string().optional(),
  principalRemarks: z.string().optional(),
  readyDate: z.string().optional(),
  attachedDocumentId: z.string().optional()
});

/**
 * PATCH /api/documents/requests/:id
 * Update a document request (e.g. approve, reject, mark ready).
 */
router.patch('/requests/:id', requirePermissions('document:approve'), async (req: Request, res: Response, next: NextFunction) => {
  try {
    const id = req.params.id;
    const input = updateDocumentRequestSchema.parse(req.body);
    const actorId = ((req as any).user as AuthenticatedUser).id;
    const correlationId = (req as any).correlationId;

    const existing = await prisma.documentRequest.findUnique({ where: { id } });
    if (!existing) {
      throw new AppError(404, 'NOT_FOUND', 'Document request not found.');
    }

    const userRoles = ((req as any).user as AuthenticatedUser).roles;
    const isAdmin = userRoles.includes('Admin') || userRoles.includes('ITAdmin');
    const dataToUpdate: any = {};

    // --- NEW SERVER-SIDE STATE MACHINE VALIDATION ---
    if (input.status !== undefined || input.currentStage !== undefined) {
      if (input.status === undefined || input.currentStage === undefined) {
        throw new AppError(422, 'UNPROCESSABLE_ENTITY', 'Both status and currentStage must be provided together.');
      }
      
      const reqStatus = input.status;
      const reqStage = input.currentStage;
      const currentStatus = existing.status;
      const currentStage = existing.current_stage;

      // Status/Stage Consistency Check
      const isValidConsistency = 
        (reqStatus === 'Teacher Approved' && reqStage === 2) ||
        (reqStatus === 'Teacher Rejected' && reqStage === 1) ||
        (reqStatus === 'Principal Approved' && reqStage === 3) ||
        (reqStatus === 'Ready for Pickup' && reqStage === 4) ||
        (reqStatus === 'Completed' && reqStage === 4);
        
      if (!isValidConsistency) {
         throw new AppError(422, 'UNPROCESSABLE_ENTITY', `Invalid status/stage combination: ${reqStatus} (stage ${reqStage})`);
      }

      let isAllowed = false;

      // Check transitions by role
      if (isAdmin) {
        const allValidTransitions = 
          (currentStatus === 'Submitted' && currentStage === 1 && (reqStatus === 'Teacher Approved' || reqStatus === 'Teacher Rejected' || reqStatus === 'Principal Approved' || reqStatus === 'Ready for Pickup')) ||
          (currentStatus === 'Teacher Approved' && currentStage === 2 && (reqStatus === 'Principal Approved' || reqStatus === 'Teacher Rejected')) ||
          (currentStatus === 'Principal Approved' && currentStage === 3 && (reqStatus === 'Ready for Pickup' || reqStatus === 'Completed')) ||
          (currentStatus === 'Ready for Pickup' && currentStage === 4 && reqStatus === 'Completed');
        if (allValidTransitions) isAllowed = true;
      }

      if (!isAllowed && userRoles.includes('Teacher')) {
        if (currentStatus === 'Submitted' && currentStage === 1) {
          if (reqStatus === 'Teacher Approved' || reqStatus === 'Teacher Rejected') {
            isAllowed = true;
          }
        }
      }

      if (!isAllowed && userRoles.includes('Principal')) {
        if (currentStatus === 'Teacher Approved' && currentStage === 2) {
          if (reqStatus === 'Principal Approved' || reqStatus === 'Teacher Rejected') {
            isAllowed = true;
          }
        }
        if (currentStatus === 'Submitted' && currentStage === 1) {
          if (reqStatus === 'Principal Approved' || reqStatus === 'Ready for Pickup') {
            isAllowed = true; // Registrar-routed shortcut
          }
        }
        if ((currentStatus === 'Principal Approved' && currentStage === 3) || 
            (currentStatus === 'Ready for Pickup' && currentStage === 4)) {
          if (reqStatus === 'Completed') {
            isAllowed = true; // Upload/scan completion
          }
        }
      }

      if (!isAllowed && userRoles.includes('Registrar')) {
        if (currentStatus === 'Principal Approved' && currentStage === 3) {
          if (reqStatus === 'Ready for Pickup') {
            isAllowed = true;
          }
        }
        if (currentStatus === 'Ready for Pickup' && currentStage === 4) {
          if (reqStatus === 'Completed') {
            isAllowed = true;
          }
        }
      }

      if (!isAllowed) {
        throw new AppError(422, 'UNPROCESSABLE_ENTITY', `Unauthorized transition from ${currentStatus} (stage ${currentStage}) to ${reqStatus} (stage ${reqStage})`);
      }

      dataToUpdate.status = reqStatus;
      dataToUpdate.current_stage = reqStage;
    }

    // --- FIELD-LEVEL VALIDATION ---
    if (input.teacherApprovedDate !== undefined && (isAdmin || userRoles.includes('Teacher'))) {
      dataToUpdate.teacher_approved_date = new Date(input.teacherApprovedDate);
    }
    if (input.teacherRemarks !== undefined && (isAdmin || userRoles.includes('Teacher'))) {
      dataToUpdate.teacher_remarks = input.teacherRemarks;
    }
    if (input.principalApprovedDate !== undefined && (isAdmin || userRoles.includes('Principal'))) {
      dataToUpdate.principal_approved_date = new Date(input.principalApprovedDate);
    }
    if (input.principalRemarks !== undefined && (isAdmin || userRoles.includes('Principal'))) {
      dataToUpdate.principal_remarks = input.principalRemarks;
    }
    if (input.readyDate !== undefined && (isAdmin || userRoles.includes('Principal') || userRoles.includes('Registrar'))) {
      dataToUpdate.ready_date = new Date(input.readyDate);
    }
    if (input.attachedDocumentId !== undefined && (isAdmin || userRoles.includes('Principal'))) {
      dataToUpdate.attached_document_id = input.attachedDocumentId;
    }

    const updated = await prisma.documentRequest.update({
      where: { id },
      data: dataToUpdate
    });

    await createAuditLog({
      actorUserId: actorId,
      action: 'DOCUMENT_REQUEST_UPDATED',
      resourceType: 'document_request',
      resourceId: updated.id,
      newState: input,
      correlationId,
    });

    res.json({ success: true, data: updated });
  } catch (err) {
    next(err);
  }
});

/**
 * POST /api/documents/:id/presign-download
 * Generate a short-lived presigned URL for document download.
 * Requires proper authorization to view the document.
 */
router.post('/:id/presign-download', requirePermissions('document:read'), async (req: Request, res: Response, next: NextFunction) => {
  try {
    const documentId = req.params.id as string;
    const actorId = ((req as any).user as AuthenticatedUser).id;
    const correlationId = (req as any).correlationId;

    const document = await prisma.document.findUnique({
      where: { id: documentId }
    });

    if (!document) {
      throw new AppError(404, 'NOT_FOUND', 'Document not found.');
    }

    // Verify the user has the right to access THIS specific document
    const authUser = (req as any).user as AuthenticatedUser;

    if (authUser.roles.includes('Student')) {
      const student = await prisma.student.findUnique({ where: { user_id: authUser.id } });
      if (!student) {
        throw new AppError(403, 'FORBIDDEN', 'Student profile not found.');
      }
      
      const isUploader = document.uploaded_by === authUser.id;
      
      const docRequest = await prisma.documentRequest.findFirst({
        where: { attached_document_id: document.id, student_id: student.id }
      });
      
      const excuse = await prisma.excuseLetter.findFirst({
        where: { document_id: document.id, student_id: student.id }
      });

      if (!isUploader && !docRequest && !excuse) {
        throw new AppError(403, 'FORBIDDEN', 'You do not have access to this document.');
      }
    } else if (!authUser.permissions.includes('document:read')) {
      if (document.uploaded_by !== authUser.id) {
        throw new AppError(403, 'FORBIDDEN', 'You do not have permission to read this document.');
      }
    }

    // Generate a temporary JWT-backed URL to serve the file
    const secret = process.env.JWT_SECRET || 'fallback-secret';
    // Expire in 5 minutes (standard presigned URL expiry)
    const token = jwt.sign({ documentId: document.id }, secret, { expiresIn: '5m' });
    const localUrl = `/api/documents/serve?token=${token}`;

    await createAuditLog({
      actorUserId: actorId,
      action: 'DOCUMENT_DOWNLOAD_URL_GENERATED',
      resourceType: 'document',
      resourceId: document.id,
      correlationId,
    });

    res.json({ success: true, data: { url: localUrl, expires_in: 300 } });
  } catch (err) {
    next(err);
  }
});

export default router;
